### PR TITLE
Template literals for pagespeed.js

### PR DESCRIPTION
**Pull request by tarungarg546**
Just a small fix .

:tophat:

### CODE REVIEW

**Comment by caueops** [comment]
Hmmm. I'm not sure if is a best practice; We're not using the template literal on the best way in this case... I'm looking at one submodule for `querystring`

**Comment by tarungarg546** [comment]
What do you mean by best practice for template literals. Any references where best practices defined would be good for all.

Second why do we need to inject a module/sub-module when we are  doing good when we wrote things in vanilla way.

**Comment by caueops** [comment]
I believe in the power of submodules, where we can simply use what other people did.
Why we develop something of which there already that was done well? It makes no sense to me..

**Comment by tarungarg546** [comment]
Another option could be instead or array and join thing...we just write everything in one line with template literals but that would make code look ugly though better in terms of complexity becuase `.join()` brings `O(n)` complexity with it.

**Comment by tarungarg546** [comment]
I think we need libraries to make our work easier and doing something that needs significant effort to do on our own , either of above is not true in our case.

And libaries are also built by humans.

**Comment by tarungarg546** [comment]
`Use libararies when you want to build something quick & get the work done while try to do on your own when you want to learn new things that where you know why would you need library and why certain things wont work as expected in our case`. And here i cant see any scenerio as such now where things wont work as we expects.

And people learn from mistakes.

**Comment by caueops** [comment]
Yeah. But, think with me. Library is very difference of small packages and I really prefer to use small packages and create something with this..

So, It's very valid create your packages for study, understand how it works, among others. :)

**Comment by tarungarg546** [comment]
That's a difference of opinion.
I always want to do everything in vanilla where-ever possible it helps me grow and learn.

**Comment by caueops** [comment]
Yeeah @tarungarg546 Me too. We're talking about the same thing 😄 
I think the best option is to always use pure javascript. Only I commented that if someone has done this is the best option 👍

**Pull request closed without merging**
